const $=id=>document.getElementById(id),enc=new TextEncoder();
const TRUSTED_KEYS=Object.freeze({'demo-rft-trust-001':'yVfl8UUbbSnu6cRBkn4dRadJWcZxvm9XDU3+jFluNWA='});
const signedPayload='{"anchor":"8f4b-demo-anchor","claim":"synthetic agent run integrity","run_id":"demo-allow-001","scope":"signed-evidence"}';
const signedPacket={name:'Signed + intact',payload:signedPayload,stored_hash:'f4dad503625786906ffe7934e3e83bb7bf5cafc49a9dd4cae679b3716529ec21',key_id:'demo-rft-trust-001',signature:'fJnTHFmUAC9UeLv5k92vqAnZ9Sa6FOIozCF++Zu1RqXi0+b6kbli9OFDDPiTpuwLfQ2/lNhvADDG2GaTcSQJCQ==',scope:'signed-evidence'};
const substitutedPayload='{"anchor":"8f4b-demo-anchor","claim":"attacker substituted signer","run_id":"demo-substitute-001","scope":"signed-evidence"}';
const substitutedPacket={name:'Self-signed + untrusted key',payload:substitutedPayload,stored_hash:'e5c4780418c3b34d7fa39fe76c80c6a08187c74ed467cffd0c941adc8fbd637a',key_id:'attacker-demo-key',presented_public_key:'YH0PeHL+CHWbRePOl8fF/IEqri/Tt0cto23vSmio4Iw=',signature:'1YPzkEdxsyZmn2J0TS6y939g3VdYU4tT8DKlLRXvmedNkkJvtb7yQHHxe1u7iLohNamWXa9jHyMJlkCQODnSDA==',scope:'signed-evidence'};
let packets={},selected='signed',currentDecision='NOT_VERIFIED';
async function sha(t){const b=await crypto.subtle.digest('SHA-256',enc.encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}function b64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function init(){const legacyPayload='{"claim":"legacy synthetic evidence","run_id":"demo-hold-001","scope":"integrity-only"}',legacyHash=await sha(legacyPayload);packets={signed:signedPacket,legacy:{name:'Legacy + intact',payload:legacyPayload,stored_hash:legacyHash,key_id:'',signature:'',scope:'integrity-only'},tampered:{...signedPacket,name:'Signed + altered',payload:'{"anchor":"8f4b-demo-anchor","claim":"ALTERED agent run integrity","run_id":"demo-allow-001","scope":"signed-evidence"}'},substituted:substitutedPacket};show('signed')}
function show(key){selected=key;currentDecision='NOT_VERIFIED';document.querySelectorAll('.packet').forEach(b=>b.classList.toggle('selected',b.dataset.packet===key));const p=packets[key];$('packetTitle').textContent=p.name;$('payload').textContent=p.payload;$('storedHash').textContent=p.stored_hash;$('keyId').textContent=p.key_id||'not present';$('presentedKey').textContent=p.presented_public_key||'not supplied';$('signature').textContent=p.signature||'not present';resetDecision()}
function resetDecision(){$('gateSeal').className='seal neutral';$('decisionWord').textContent='READY';$('decisionScope').textContent='Run the gate to evaluate this packet.';['hashCheck','trustCheck','sigCheck','scopeCheck'].forEach(id=>$(id).textContent='—');$('meaningTitle').textContent='No decision yet.';$('meaningText').textContent='TrustStack should not turn incomplete or self-asserted evidence into stronger evidence by wording alone.';$('downloadBtn').disabled=true}
async function verifyEd25519(publicKey,signature,payload){try{const key=await crypto.subtle.importKey('raw',b64(publicKey),{name:'Ed25519'},false,['verify']);return{supported:true,ok:await crypto.subtle.verify({name:'Ed25519'},key,b64(signature),enc.encode(payload)),malformed:false}}catch(e){if(e?.name==='NotSupportedError')return{supported:false,ok:false,malformed:false};return{supported:true,ok:false,malformed:true}}}
async function gate(){const p=packets[selected],freshHash=await sha(p.payload),hashOK=freshHash===p.stored_hash;$('hashCheck').textContent=hashOK?'PASS':'FAIL';$('scopeCheck').textContent=p.scope.toUpperCase();if(!hashOK){$('trustCheck').textContent='NOT EVALUATED';$('sigCheck').textContent='NOT ADMITTED';decide('block','BLOCK','Payload commitment failed.','The stored SHA-256 commitment does not match the current payload. This evidence must be rejected as altered.');return}if(!p.signature){$('trustCheck').textContent='NO SIGNER';$('sigCheck').textContent='NOT PRESENT';decide('hold','HOLD','Integrity only · no signature','The packet is internally intact but lacks signed evidence required for the strongest gate.');return}const trustedPublicKey=TRUSTED_KEYS[p.key_id];if(!trustedPublicKey){$('trustCheck').textContent='UNTRUSTED KEY ID';$('sigCheck').textContent='NOT ADMITTED';decide('block','BLOCK','Signer is not in the verifier trust store','A packet cannot introduce its own trust anchor.');return}$('trustCheck').textContent='PINNED KEY';const sig=await verifyEd25519(trustedPublicKey,p.signature,p.payload);if(!sig.supported){$('sigCheck').textContent='BROWSER UNSUPPORTED';decide('hold','HOLD','Ed25519 verification unavailable here','The browser cannot complete the signature check.');return}if(sig.malformed){$('sigCheck').textContent='MALFORMED';decide('block','BLOCK','Signature material is malformed','Malformed or undecodable cryptographic material is evidence failure, not browser non-support.');return}$('sigCheck').textContent=sig.ok?'PASS':'FAIL';if(sig.ok)decide('allow','ALLOW','Integrity + trusted-key signature verified','The payload commitment and signature verify against the verifier-owned demo trust anchor.');else decide('block','BLOCK','Trusted-key signature verification failed','The payload hash is intact, but its signature does not verify against the trusted Ed25519 key.')}
function decide(kind,word,scope,title){currentDecision=word;$('gateSeal').className=`seal ${kind}`;$('decisionWord').textContent=word;$('decisionScope').textContent=scope;$('meaningTitle').textContent=word==='ALLOW'?'Evidence meets this demo gate.':word==='HOLD'?'Evidence is inspectable but incomplete.':'Evidence fails the gate.';$('meaningText').textContent=title;$('downloadBtn').disabled=false}
async function download(){if(currentDecision==='NOT_VERIFIED')return;const artifact={format:'rftsystems4ai-browser-truststack-decision-v1',packet_state:selected,packet:structuredClone(packets[selected]),decision:{verdict:currentDecision,scope:$('decisionScope').textContent}};const bundle=await RFTDemoBundle.build('truststack',artifact,currentDecision),blob=new Blob([JSON.stringify(bundle,null,2)+'\n'],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`truststack_${selected}_${currentDecision.toLowerCase()}_rftsystems4ai.json`;a.click();URL.revokeObjectURL(u)}
document.querySelectorAll('.packet').forEach(b=>b.onclick=()=>show(b.dataset.packet));$('gateBtn').onclick=gate;$('downloadBtn').onclick=download;init();