const encoder=new TextEncoder();const $=id=>document.getElementById(id);let record=null,tampered=false,verificationStatus='NOT_VERIFIED';
function stable(value){if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;return JSON.stringify(value)}
async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',encoder.encode(text));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function short(h){return h?`${h.slice(0,12)}…${h.slice(-10)}`:'—'}function sessionId(){return`afr-${Date.now().toString(36)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(16)}`}
async function buildRun(){tampered=false;verificationStatus='NOT_VERIFIED';const sid=sessionId();const seed=[['prompt',{text:'Check deployment status and report only evidence-backed facts.'}],['tool_call',{tool:'status_lookup',input:{service:'agent-api'}}],['tool_result',{service:'agent-api',status:'degraded',region:'eu-west'}],['memory_write',{key:'incident.last_status',value:'degraded',reason:'tool result'}],['output',{text:'Agent API is degraded in eu-west based on the recorded status lookup.'}],['note',{checkpoint:'run_complete'}]];let prev='0'.repeat(64),events=[];for(let i=0;i<seed.length;i++){const[type,payload]=seed[i],canonical={session_id:sid,seq:i+1,event_type:type,payload,prev_hash:prev},hash=await sha256(stable(canonical));events.push({...canonical,event_hash:hash});prev=hash}record={format:'rftsystems4ai-browser-flight-record-v1',scope:'internal-sha256-chain-consistency-demo',session_id:sid,events,final_anchor:prev,trust_boundary:{external_anchor_present:false,external_anchor_verified:false,signer_identity_verified:false}};$('sessionId').textContent=sid;$('verifyBtn').disabled=false;$('tamperBtn').disabled=false;$('downloadBtn').disabled=true;$('externalAnchor').textContent='AUTHENTICATED DEMO RELEASE CONTRACT ON EXPORT';setReport('neutral','RUN RECORDED','Six synthetic events were hash-chained. Verify the stored commitments before exporting.');render()}
async function verify(){if(!record)return;let prev='0'.repeat(64),firstBad=null;for(const ev of record.events){const canonical={session_id:ev.session_id,seq:ev.seq,event_type:ev.event_type,payload:ev.payload,prev_hash:prev},expected=await sha256(stable(canonical));if((expected!==ev.event_hash||ev.prev_hash!==prev)&&firstBad===null)firstBad=ev.seq;prev=expected}if(firstBad===null&&prev===record.final_anchor){verificationStatus='PASS';setReport('good','INTERNAL CONSISTENCY PASS','Stored event commitments and final anchor match a fresh SHA-256 recomputation. The exported bundle can also be checked against the authenticated RFTSystems4Ai demo release contract.')}else{verificationStatus='FAIL';setReport('bad',`INTERNAL CONSISTENCY FAIL AT EVENT ${String(firstBad??'?').padStart(2,'0')}`,'The stored evidence no longer matches its commitment chain. The exported bundle preserves this failure for independent verification.')} $('downloadBtn').disabled=false;render(firstBad)}
function tamper(){if(!record||tampered)return;record.events[3].payload.value='healthy';tampered=true;verificationStatus='NOT_VERIFIED';$('downloadBtn').disabled=true;setReport('neutral','EVENT 04 ALTERED','The payload changed while its stored commitments remained unchanged. Verify again before exporting.');render()}
function reset(){record=null;tampered=false;verificationStatus='NOT_VERIFIED';$('sessionId').textContent='not started';$('verifyBtn').disabled=true;$('tamperBtn').disabled=true;$('downloadBtn').disabled=true;$('timeline').innerHTML='';$('anchorHash').textContent='—';$('externalAnchor').textContent='AUTHENTICATED DEMO RELEASE CONTRACT ON EXPORT';setReport('neutral','No record yet.','Build the synthetic run first.')}
function setReport(kind,title,text){$('statusBadge').className=`badge ${kind==='neutral'?'':kind}`.trim();$('statusBadge').textContent=kind==='good'?'CONSISTENT':kind==='bad'?'INCONSISTENT':title==='RUN RECORDED'?'RECORDED':'AWAITING VERIFY';$('reportTitle').textContent=title;$('reportText').textContent=text}
function render(firstBad=null){if(!record)return;$('anchorHash').textContent=record.final_anchor;$('timeline').innerHTML=record.events.map(ev=>{const cls=[ev.seq===4&&tampered?'tampered':'',firstBad&&ev.seq>=firstBad?'broken':''].filter(Boolean).join(' ');return`<article class="event ${cls}"><div class="seq">${String(ev.seq).padStart(2,'0')}</div><div class="type">${escapeHtml(ev.event_type.toUpperCase())}</div><div class="body"><p>${escapeHtml(JSON.stringify(ev.payload))}</p><code>prev ${escapeHtml(short(ev.prev_hash))}</code><code>hash ${escapeHtml(short(ev.event_hash))}</code></div></article>`}).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function download(){if(!record||verificationStatus==='NOT_VERIFIED')return;const artifact={...record,verification_note:'This artefact is independently re-checkable against the Ed25519-signed RFTSystems4Ai demo release contract bundled with the download.'};const bundle=await RFTDemoBundle.build('agent-flight-recorder',artifact,verificationStatus);const blob=new Blob([JSON.stringify(bundle,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${record.session_id}_${verificationStatus.toLowerCase()}_rftsystems4ai.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
$('buildBtn').addEventListener('click',buildRun);$('verifyBtn').addEventListener('click',verify);$('tamperBtn').addEventListener('click',tamper);$('resetBtn').addEventListener('click',reset);$('downloadBtn').addEventListener('click',download);